cc_test(
    name = "resource_test",
    srcs = ["ResourceTest.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//:ga_lib",
    ],
)

cc_test(
    name = "task_test",
    srcs = ["TaskTest.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//:ga_lib",
    ],
)

cc_test(
    name = "project_test",
    srcs = ["ProjectTest.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//:ga_lib",
    ],
)
