cc_test(
    name = "resource_test",
    size = "small",
    srcs = ["ResourceTest.cpp"],
    deps = [
        "//:ms_rcpsp_lib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "task_test",
    size = "small",
    srcs = ["TaskTest.cpp"],
    deps = [
        "//:ms_rcpsp_lib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "project_test",
    size = "small",
    srcs = ["ProjectTest.cpp"],
    deps = [
        "//:ms_rcpsp_lib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "simple_schedule_test",
    size = "small",
    srcs = ["SimpleScheduleTest.cpp"],
    deps = [
        "//:ms_rcpsp_lib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "prio_schedule_test",
    size = "small",
    srcs = ["PrioScheduleTest.cpp"],
    deps = [
        "//:ms_rcpsp_lib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "project_reader_test",
    size = "small",
    srcs = ["ProjectReaderTest.cpp"],
    deps = [
        "//:ms_rcpsp_lib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "schedule_writer_test",
    size = "small",
    srcs = ["ScheduleWriterTest.cpp"],
    deps = [
        "//:ms_rcpsp_lib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "validator_test",
    size = "small",
    srcs = ["ValidatorTest.cpp"],
    deps = [
        "//:ms_rcpsp_lib",
        "@googletest//:gtest_main",
    ],
)
